# -*- coding: utf-8 -*-
"""newtextblob.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J9CfbPbPQKRDSF9EqFPuMQxugf0fmLy-
"""

import pandas as pd
from textblob import TextBlob

# Load the CSV file
df = pd.read_csv('C:/Users/faizf/Downloads/Final code files/Lucid_motors-RAW_tweets.csv')

# Add a new column for sentiment category
df['sentiment_category'] = ''

# Perform sentiment analysis using TextBlob
for i, row in df.iterrows():
    tweet = row['content']
    sentiment = TextBlob(tweet).sentiment.polarity

    # Classify sentiment into categories
    if sentiment > 0.3:
        df.at[i, 'sentiment_category'] = 'Very Positive'
    elif sentiment > 0:
        df.at[i, 'sentiment_category'] = 'Positive'
    elif sentiment == 0:
        df.at[i, 'sentiment_category'] = 'Neutral'
    elif sentiment > -0.3:
        df.at[i, 'sentiment_category'] = 'Negative'
    else:
        df.at[i, 'sentiment_category'] = 'Very Negative'

# Define a mapping dictionary for sentiment categories
sentiment_mapping = {
    'Very Positive': 4,
    'Positive': 3,
    'Neutral': 2,
    'Negative': 1,
    'Very Negative': 0
}

# Convert sentiment categories to numerical values
df['sentiment_numeric'] = df['sentiment_category'].map(sentiment_mapping)

# Save the modified DataFrame to a new CSV file
df.to_csv('C:/Users/faizf/Downloads/Final code files/tweets_with_sentiment.csv', index=False)

