# -*- coding: utf-8 -*-
"""wordcloud.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10_pJ6t6KIhGMaxzmX-_HNMa2PjmBnpTR
"""

#File authorization from google drive
from google.colab import drive
drive.mount('/content/drive')

!pip install pandas
!pip install matplotlib
!pip install wordcloud

import pandas as pd
from wordcloud import WordCloud
import matplotlib.pyplot as plt

# Load the cleaned data
path = '/content/drive/MyDrive/data/new/cleaned_tweet_data.csv'
df = pd.read_csv(path, encoding='ISO-8859-1', on_bad_lines='skip')

# Combine all tweet content into a single string
all_tweets = ' '.join(df['content'])

# Remove words containing 'Ã'
all_tweets = ' '.join(word for word in all_tweets.split() if 'Ã' not in word)

# Generate the word cloud
wordcloud = WordCloud(width=800, height=400, background_color='white').generate(all_tweets)

# Plot the word cloud
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.show()